# Generated by Django 3.2 on 2023-03-06 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(default='')),
                ('originalImage', models.ImageField(upload_to='image')),
                ('address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('TotalBeds', models.IntegerField(default=0)),
                ('Phone', models.CharField(max_length=500, unique=True)),
                ('web', models.CharField(default='', max_length=500)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Single', models.IntegerField(default=0)),
                ('Double', models.IntegerField(default=0)),
                ('Triple', models.IntegerField(default=0)),
                ('Sweet', models.IntegerField(default=0)),
                ('chalet', models.IntegerField(default=0)),
                ('villa', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TouristPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('type', models.CharField(max_length=500)),
                ('description', models.TextField(default='')),
                ('coordinatesX', models.FloatField()),
                ('coordinatesY', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('originalImage', models.ImageField(upload_to='image')),
                ('video', models.FileField(upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
            ],
            options={
                'unique_together': {('coordinatesX', 'coordinatesY')},
            },
        ),
        migrations.CreateModel(
            name='TourismImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, unique=True, upload_to='image')),
                ('touristPlaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FayTourApp.touristplaces')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, unique=True, upload_to='image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FayTourApp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RateTouristPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('touristPlaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.touristplaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'touristPlaces')},
                'index_together': {('user', 'touristPlaces')},
            },
        ),
        migrations.CreateModel(
            name='RateHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hotel')},
                'index_together': {('user', 'hotel')},
            },
        ),
    ]
