# Generated by Django 3.2 on 2023-03-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0003_alter_hotel_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='created_by',
            new_name='user',
        ),
    ]
